export const CATEGORIES_DATA = [
  {
    id: "indian-masalas",
    name: "Indian Masalas",
    weight: "250g",
    icon: "🌶️",
    image: "/category-masalas.png",
    color: "bg-orange-500/10 text-orange-600",
    products: [
      { id: "curry-masala", name: "Curry masala", price: 249, rating: 4.8, reviews: 124, description: "Authentic blend of traditional Indian spices for the perfect curry flavor." },
      { id: "mutton-masala", name: "Mutton masala", price: 249, rating: 4.7, reviews: 89, description: "Specially formulated spice mix to enhance the richness of mutton dishes." },
      { id: "chicken-masala", name: "Chicken masala", price: 259, rating: 4.9, reviews: 256, description: "A balanced spice mix for flavorful and aromatic chicken preparations." },
      { id: "chicken-65-masala", name: "Chicken 65 masala", price: 249, rating: 4.6, reviews: 78, description: "Perfectly spiced mix for making the classic crispy South Indian Chicken 65." },
      { id: "biriyani-masala", name: "Biriyani masala (100g)", price: 130, rating: 5.0, reviews: 412, description: "Premium blend of whole and ground spices for restaurant-style biriyani at home." },
      { id: "coriander-powder", name: "Coriander powder", price: 125, rating: 4.5, reviews: 56, description: "Pure, aromatic coriander seeds ground to perfection." },
      { id: "red-chilli-powder", name: "Red chilli powder", price: 199, rating: 4.8, reviews: 145, description: "High-quality sun-dried red chillies for heat and vibrant color." },
      { id: "kulambu-thool", name: "Kulambu milagai Thool", price: 225, rating: 4.7, reviews: 92, description: "Traditional Tamil-style chili powder blend for all types of kulambu." },
      { id: "sambar-powder", name: "Sambar powder", price: 225, rating: 4.9, reviews: 187, description: "The secret to authentic, flavorful South Indian sambar." },
      { id: "turmeric-powder", name: "Turmeric powder", price: 249, rating: 4.8, reviews: 210, description: "Pure, high-curcumin turmeric powder for health and color." },
    ],
  },
  {
    id: "malt-varieties",
    name: "Malt Varieties",
    weight: "250g",
    icon: "🥛",
    image: "/category-herbal.png",
    color: "bg-amber-500/10 text-amber-600",
    products: [
      { id: "ragi-choco-malt", name: "Ragi Choco Malt", price: 250, rating: 4.9, reviews: 156, description: "Healthy and delicious chocolate flavored ragi malt for all ages." },
      { id: "abc-malt", name: "ABC Malt", price: 299, rating: 5.0, reviews: 342, description: "Apple, Beetroot, and Carrot combined into a powerful health drink." },
      { id: "carrot-malt", name: "Carrot Malt", price: 299, rating: 4.8, reviews: 88, description: "Rich in Vitamin A, this carrot malt is great for eye health and immunity." },
      { id: "beetroot-malt", name: "Beetroot Malt", price: 299, rating: 4.7, reviews: 123, description: "Iron-rich beetroot malt for natural stamina and blood health." },
      { id: "red-banana-malt", name: "Red Banana Malt", price: 310, rating: 4.9, reviews: 201, description: "Unique and nutritious malt made from premium red bananas." },
    ],
  },
  {
    id: "rice-mix-powders",
    name: "Rice Mix Powders",
    weight: "250g",
    icon: "🍚",
    image: "/category-grocery.png",
    color: "bg-blue-500/10 text-blue-600",
    products: [
      { id: "idly-dosa-podi", name: "Idly Dosa podi", price: 199, rating: 5.0, reviews: 520, description: "The classic gunpowder for idly and dosa, made with premium lentils." },
      { id: "paruppu-podi", name: "Paruppu podi", price: 199, rating: 4.8, reviews: 145, description: "Nutritious roasted lentil powder to mix with hot rice and ghee." },
      { id: "poondu-saadha-podi", name: "Poondu Saadha podi", price: 225, rating: 4.9, reviews: 213, description: "Flavorful garlic rice mix powder for a quick and healthy meal." },
    ],
  },
  {
    id: "plain-powders",
    name: "Plain Powders",
    weight: "100g",
    icon: "🍃",
    image: "/category-masalas.png",
    color: "bg-green-500/10 text-green-600",
    products: [
      { id: "tomato-powder", name: "Tomato powder", price: 99, rating: 4.5, reviews: 45, description: "Dehydrated pure tomato powder for soups, sauces, and seasoning." },
      { id: "onion-powder", name: "Onion powder", price: 99, rating: 4.6, reviews: 38, description: "Pure white onion powder for easy cooking and intense flavor." },
    ],
  },
  {
    id: "thokku-varieties",
    name: "Thokku Varieties",
    weight: "200g",
    icon: "🥫",
    image: "/category-masalas.png",
    color: "bg-red-500/10 text-red-600",
    products: [
      { id: "pirandai-thokku", name: "Pirandai Thokku", price: 195, rating: 4.9, reviews: 167, description: "Medicinal Pirandai (Adamant Creeper) thokku for bone health and digestion." },
      { id: "tomato-thokku", name: "Tomato Thokku", price: 165, rating: 4.7, reviews: 89, description: "Spicy and tangy tomato pickle-style thokku for rice and tiffins." },
    ],
  },
  {
    id: "heritage-harvest",
    name: "The Heritage Harvest",
    icon: "🌾",
    image: "/category-grocery.png",
    color: "bg-emerald-500/10 text-emerald-600",
    products: [
      { id: "ragi-flour", name: "Ragi Flour (500g)", price: 149, rating: 4.8, reviews: 234, description: "Finely ground finger millet flour for healthy porridges and rotis." },
      { id: "sprouted-ragi-flour", name: "Sprouted Ragi Flour (500g)", price: 230, rating: 5.0, reviews: 456, description: "Sprouted ragi flour with increased bio-availability of nutrients." },
    ],
  },
  {
    id: "nurtured-by-nature",
    name: "Nurtured by Nature",
    icon: "🌿",
    image: "/category-herbal.png",
    color: "bg-lime-500/10 text-lime-600",
    products: [
      { id: "herbal-face-pack", name: "Herbal Face Pack (200g)", price: 270, rating: 4.9, reviews: 189, description: "Traditional herbal blend for glowing skin and natural detoxification." },
      { id: "herbal-hair-oil", name: "Herbal Hair Oil (200ml)", price: 375, rating: 4.8, reviews: 267, description: "Cold-pressed oil infused with over 21 medicinal herbs for hair growth." },
    ],
  },
  {
    id: "golden-pantry",
    name: "The Golden Pantry",
    icon: "🍯",
    image: "/category-gourmet.png",
    color: "bg-yellow-500/10 text-yellow-600",
    products: [
      { id: "nattu-mattu-ghee", name: "Nattu Mattu Ghee 500ml", price: 1250, rating: 5.0, reviews: 890, description: "Pure A2 desi cow ghee made through the traditional Bilona method." },
      { id: "honey", name: "Honey 250ml", price: 350, rating: 4.9, reviews: 432, description: "100% pure, unpasteurized forest honey with all natural enzymes intact." },
    ],
  },
  {
    id: "muesli-varieties",
    name: "Muesli Varieties",
    weight: "250g",
    icon: "🥣",
    image: "/category-snacks.png",
    color: "bg-indigo-500/10 text-indigo-600",
    products: [
      { id: "honey-muesli", name: "Honey Muesli", price: 150, rating: 4.6, reviews: 67, description: "Healthy breakfast cereal with oats, nuts, and natural honey sweetness." },
    ],
  },
  {
    id: "baby-products",
    name: "Baby Products",
    weight: "250g",
    icon: "👶",
    image: "/category-herbal.png",
    color: "bg-pink-500/10 text-pink-600",
    products: [
      { id: "sprouted-health-mix", name: "Sprouted Health Mix", price: 349, rating: 5.0, reviews: 567, description: "The ultimate traditional Sathu Maavu for babies and growing children." },
    ],
  },
  {
    id: "cookies-varieties",
    name: "Cookies Varieties",
    weight: "250g",
    icon: "🍪",
    image: "/category-snacks.png",
    color: "bg-rose-500/10 text-rose-600",
    products: [
      { id: "murunga-cookies", name: "Murunga Cookies", price: 550, rating: 4.9, reviews: 142, description: "Innovative health cookies made with iron-rich Moringa leaves." },
    ],
  },
  {
    id: "soup-mix-powders",
    name: "Soup Mix Powders",
    weight: "250g",
    icon: "🥣",
    image: "/category-mixes.png",
    color: "bg-cyan-500/10 text-cyan-600",
    products: [
      { id: "mudavattukal-soup", name: "Mudavattukal Soup Mix", price: 320, rating: 4.8, reviews: 95, description: "Traditional medicinal soup for joint pains and immunity." },
    ],
  },
  {
    id: "wheat-pastas",
    name: "Wheat Pastas",
    weight: "230g",
    icon: "🍝",
    image: "/category-mixes.png",
    color: "bg-orange-500/10 text-orange-700",
    products: [
      { id: "moringa-pasta", name: "Moringa Pasta", price: 135, rating: 4.7, reviews: 78, description: "Healthy alternative to regular pasta, infused with drumstick leaf extract." },
    ],
  },
  {
    id: "laddu-varieties",
    name: "Laddu Varieties",
    weight: "Per Pcs",
    icon: "🍬",
    image: "/category-snacks.png",
    color: "bg-orange-400/10 text-orange-800",
    products: [
      { id: "kambu-laddu", name: "Kambu Laddu", price: 12, rating: 5.0, reviews: 120, description: "Nutritious pearl millet sweet treat made with jaggery." },
    ],
  },
  {
    id: "pancake-mix",
    name: "Pancake Mix",
    weight: "250g",
    icon: "🥞",
    image: "/category-mixes.png",
    color: "bg-violet-500/10 text-violet-700",
    products: [
      { id: "strawberry-pancake", name: "Strawberry Pancake Mix", price: 315, rating: 4.6, reviews: 54, description: "Easy to make fluffy pancakes with natural strawberry flavor." },
    ],
  },
];
